[book]
authors = ["Dyn upcast Members"]
language = "en"
multilingual = false
src = "."
title = "Dyn upcast initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/dyn-upcast-initiative"
