[book]
authors = ["Dyn upcasting coercion Initiative Members"]
language = "en"
multilingual = false
src = "."
title = "Dyn upcasting coercion Initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/nikomatsakis/dyn-upcasting-coercion-initiative"
